name: Deploy API Image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/manuel-materazzo/sd-forge:latest --tag ghcr.io/manuel-materazzo/sd-forge:${{github.action_ref}}
          docker push ghcr.io/manuel-materazzo/sd-forge:latest
          docker push ghcr.io/manuel-materazzo/sd-forge:${{github.action_ref}}